export const roomListErrorCodes = {
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  INVALID_ROOM_NAME: 'INVALID_ROOM_NAME',
  CREATE_ROOM_FAILED: 'CREATE_ROOM_FAILED',
  FETCH_ROOMS_FAILED: 'FETCH_ROOMS_FAILED',
  LEAVE_ROOM_FAILED: 'LEAVE_ROOM_FAILED',
  NOT_PARTICIPANT: 'NOT_PARTICIPANT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DUPLICATE_ROOM_NAME: 'DUPLICATE_ROOM_NAME',
} as const;

export type RoomListErrorCode =
  (typeof roomListErrorCodes)[keyof typeof roomListErrorCodes];
