export const messageErrorCodes = {
  // Message operations
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  INVALID_MESSAGE_CONTENT: 'INVALID_MESSAGE_CONTENT',
  MESSAGE_CREATE_FAILED: 'MESSAGE_CREATE_FAILED',
  MESSAGE_UPDATE_FAILED: 'MESSAGE_UPDATE_FAILED',
  MESSAGE_DELETE_FAILED: 'MESSAGE_DELETE_FAILED',

  // Room operations
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  NOT_ROOM_PARTICIPANT: 'NOT_ROOM_PARTICIPANT',
  FETCH_SNAPSHOT_FAILED: 'FETCH_SNAPSHOT_FAILED',
  FETCH_HISTORY_FAILED: 'FETCH_HISTORY_FAILED',

  // Long Polling
  POLLING_FAILED: 'POLLING_FAILED',
  INVALID_VERSION: 'INVALID_VERSION',

  // Like operations
  LIKE_FAILED: 'LIKE_FAILED',
  FETCH_LIKES_FAILED: 'FETCH_LIKES_FAILED',

  // Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Validation
  INVALID_REQUEST: 'INVALID_REQUEST',
  CONTENT_TOO_LONG: 'CONTENT_TOO_LONG',
} as const;

export type MessageErrorCode =
  (typeof messageErrorCodes)[keyof typeof messageErrorCodes];
